apiVersion: batch/v1
kind: Job
metadata:
  name: tsunami-scanner-100.200.100.200
  namespace: kube-system
  labels:
    jobgroup: tsunami-scanner
spec:
  template:
    metadata:
      name: tsunami-scanner
      labels:
        jobgroup: tsunami-scanner
    spec:
      containers:
      - name: scanner
        image: tsunami
        args: ["sh", "-c", "--ip-v4-target=100.200.100.200"]
      restartPolicy: Never