apiVersion: batch/v1
kind: Job
metadata:
  name: tsunami-scanner-$IP
  namespace: kube-system
  labels:
    jobgroup: tsunami-scanner
spec:
  template:
    metadata:
      name: tsunami-scanner
      labels:
        jobgroup: tsunami-scanner
    spec:
      containers:
      - name: scanner
        image: tsunami
        imagePullPolicy: IfNotPresent
        args: ["sh", "-c", "--ip-v4-target=$IP"]
      restartPolicy: Never